name: unknown_contacts_app
description: App para gestionar contactos no guardados y exportar a Excel
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Actualizado para compatibilidad con Flutter 3.x y Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  
  # Permisos
  permission_handler: ^11.3.1
  
  # Contactos
  contacts_service: ^0.6.3
  
  # Historial de llamadas
  call_log: ^6.0.0

  uses-material-design: true
  # Excel
  excel: ^4.0.6

  # Archivos y compartir
  path_provider: ^2.1.2
  share_plus: ^7.2.2

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: